services:
  postgres:
    image: 'apache/age:latest'
    environment:
      - 'POSTGRES_DB=items'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - items-db:/var/lib/postgresql/data
      - ./src/main/resources/init-sql.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  items-db:
    driver: local
